### ISSUE TITLE
Create a Timepoints excel file in sharepoint

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/microbe-central#1]
**Description of the issue**

After the conversation on the DWG on 04/07/2024, it is very clear that we need to clarify the timepoints for the samples. Samples have been collected by DSMZ, then pooled, then distributed, and then each group has performed cryopreservation and extracted the library at different points in time.

Therefore, we have decided to lay down an excel spreadsheet with the samples and their collection/analysis date.

**Comment by ESapenaVentura** [comment]
The spreadsheet is available here: [Timepoints table](https://rtdservices001.sharepoint.com/:x:/r/sites/microbe/Shared%20Documents/3-Workplan%20-%20Workpackages/Workpackage%203%20(Data%20Infra,%20EMBL)/Timepoints_table.xlsx?d=wab952ea5561c457eb857fe71453eb159&csf=1&web=1&e=ybBdfl)

Katrin has already amended two of their samples and also suggested a new column

I will add it today

**Comment by Jeena-Rajan** [comment]
Ensure all dates are in the format YYYY-MM-DD

**Comment by ESapenaVentura** [comment]
Turns out the dates were auto-formatted after importing to sharepoint into american format! Fixed that now

Added the column - Should we ask for people to fill out the "planned" timepoints?

In any case, fixed the issues! I will move this to Review/QA
