### ISSUE TITLE
Confirm HMGU data is OK for MGnify

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/microbe-central#12]

**Comment by ESapenaVentura** [comment]
tl;dr of the work done so far:

- Enrique, Germana and Pamela discussed over e-mail
- Pamela sent some very useful files
- Germana to check on those files and come back to Pamela when possible

**Comment by ESapenaVentura** [comment]
Germana is trying to download Pamela's data to further verify, but this is currently blocked by https://embl.service-now.com/esc?id=ticket&table=sc_req_item&sys_id=4bc1f3df1b455e10a32b4043b24bcb17

**Comment by ESapenaVentura** [comment]
No longer blocked - The password has been updated and sent to all contributors, including Germana

**Comment by ESapenaVentura** [comment]
Germana has confirmed everything looks a-ok!
