### ISSUE TITLE
Create an agenda for a submissions workshop

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/microbe-central#16]
For the upcoming submissions workshop, it would be good to create an agenda and circulate it, to understand their needs in the submission process and how we can support them

**Comment by ESapenaVentura** [comment]
Waiting until the DWG to decide if we continue with this proposal

**Comment by Jeena-Rajan** [comment]
No needed now as discussed with MICROBE consortium. Prefer personalised support for data submission
