### ISSUE TITLE
Check DSMZ samples against BioSamples

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/microbe-central#19]
![Image](https://github.com/user-attachments/assets/6553723f-5b1c-46b8-b6dc-a265224479e0)
- Lars sent a tables of DSMZ samples already registered in BioSamples.
- There is an issue with the Biosample IDs as the metadata in BioSamples doesn't match the metadata is in the spreadsheet BioSample ID.
- Also  there is extra metadata not captured in the spreadsheet e.g. 
[SAMEA115407045](https://www.ebi.ac.uk/biosamples/samples/SAMEA115407045) which has soil type 'Histosol" in BioSamples has soil type 'Cambisol' in the spreadsheet Lars sent
This needs to be investigated (email sent on 29/10/24)

**Comment by ESapenaVentura** [comment]
This task is being captured in the harmonisation of soil metadata - The ticket has not been closed but this has been addressed (DMSZ t0)
